{
  "swagger" : "2.0",
  "info" : {
    "description" : "This is the API documentation for the COP 4331 Contact Manager App",
    "version" : "1.0.0",
    "title" : "Contact Manager App Group 7",
    "contact" : {
      "email" : "Richard.Leinecker@ucf.edu"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "COP4331-7.com",
  "basePath" : "/LAMPAPI",
  "schemes" : [ "http" ],
  "paths" : {
    "/Login.php" : {
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "Logs in to the contact manager app",
        "description" : "Logs in to contact manager app",
        "operationId" : "doLogin",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "loginItem",
          "description" : "Login",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/Login"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "404" : {
            "description" : "URL Not Found"
          }
        }
      }
    },
    "/Register.php" : {
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "Adds a user to our database",
        "description" : "Adds a user to the user database",
        "operationId" : "addUser",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "registerItem",
          "description" : "User",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/Register"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "404" : {
            "description" : "URL Not Found"
          }
        }
      }
    },
    "/Search.php" : {
      "post" : {
        "tags" : [ "Contacts" ],
        "summary" : "Searches contacts",
        "description" : "Searches contacts from contact database",
        "operationId" : "searchContacts",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "searchItem",
          "description" : "Contact Search",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/Search"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "404" : {
            "description" : "URL Not Found"
          }
        }
      }
    },
    "/Add.php" : {
      "post" : {
        "tags" : [ "Contacts" ],
        "summary" : "Adds contacts in Contacts database",
        "description" : "Adds contacts",
        "operationId" : "addContact",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "addItem",
          "description" : "Add",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/Add"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "404" : {
            "description" : "URL Not Found"
          }
        }
      }
    },
    "/Edit.php" : {
      "post" : {
        "tags" : [ "Contacts" ],
        "summary" : "Edits contacts in Contacts database",
        "description" : "Edits contacts",
        "operationId" : "editContact",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "editItem",
          "description" : "Edit",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/Edit"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "404" : {
            "description" : "URL Not Found"
          }
        }
      }
    },
    "/Delete.php" : {
      "post" : {
        "tags" : [ "Contacts" ],
        "summary" : "Deletes contacts",
        "description" : "Deletes contacts from a user",
        "operationId" : "delContact",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "deleteItem",
          "description" : "Contact Delete",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/Delete"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          },
          "404" : {
            "description" : "URL Not Found"
          }
        }
      }
    }
  },
  "definitions" : {
    "Register" : {
      "type" : "object",
      "required" : [ "Login", "Password", "firstName", "lastName" ],
      "properties" : {
        "firstName" : {
          "type" : "string",
          "example" : "Richard"
        },
        "lastName" : {
          "type" : "string",
          "example" : "Leinecker"
        },
        "Login" : {
          "type" : "string",
          "example" : "profLein05"
        },
        "Password" : {
          "type" : "string",
          "example" : "password123"
        }
      }
    },
    "Login" : {
      "type" : "object",
      "properties" : {
        "login" : {
          "type" : "string",
          "example" : "username"
        },
        "password" : {
          "type" : "string",
          "example" : "secret"
        }
      }
    },
    "Search" : {
      "type" : "object",
      "required" : [ "searchTerm", "userId" ],
      "properties" : {
        "userId" : {
          "type" : "integer",
          "example" : 1
        },
        "searchTerm" : {
          "type" : "string",
          "example" : "Chris"
        }
      }
    },
    "Add" : {
      "type" : "object",
      "required" : [ "UserID", "fields" ],
      "properties" : {
        "fields" : {
          "type" : "array",
          "example" : {
            "FirstName" : "Charles",
            "LastName" : "Darwin",
            "Email" : "charles-darwin@example.com",
            "Phone" : "407-112-1112"
          },
          "items" : {
            "type" : "string"
          }
        },
        "UserID" : {
          "type" : "integer",
          "example" : 2
        }
      }
    },
    "Edit" : {
      "type" : "object",
      "required" : [ "contactId", "fields", "input", "userId" ],
      "properties" : {
        "fields" : {
          "type" : "array",
          "example" : {
            "firstName" : 1,
            "lastName" : 1,
            "email" : 0,
            "phone" : 0
          },
          "items" : {
            "type" : "integer"
          }
        },
        "input" : {
          "type" : "array",
          "example" : {
            "firstName" : "Richard",
            "lastName" : "Leinecker",
            "email" : "",
            "phone" : ""
          },
          "items" : {
            "type" : "string"
          }
        },
        "contactId" : {
          "type" : "integer",
          "example" : 1
        },
        "userId" : {
          "type" : "integer",
          "example" : 2
        }
      }
    },
    "Delete" : {
      "type" : "object",
      "required" : [ "contactId", "userId" ],
      "properties" : {
        "userId" : {
          "type" : "integer",
          "example" : 1
        },
        "contactId" : {
          "type" : "integer",
          "example" : 1
        }
      }
    }
  }
}